# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-20 10:27
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctext', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='useradd',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('country', models.CharField(max_length=100)),
                ('profile_picture', models.FileField(upload_to=b'')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='tweet',
            name='tweetfrom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Twitter.useradd'),
        ),
        migrations.AddField(
            model_name='tweet',
            name='tweetto',
            field=models.ManyToManyField(to='Twitter.useradd'),
        ),
        migrations.AddField(
            model_name='comment',
            name='commentfrom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Twitter.useradd'),
        ),
        migrations.AddField(
            model_name='comment',
            name='commenton',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Twitter.tweet'),
        ),
    ]
